#pragma once

#include <juce_gui_basics/juce_gui_basics.h>

#include <array>

// LookAndFeelReamix — juce::LookAndFeel_V4 subclass applying the reamix.me
// design tokens to standard JUCE widgets (buttons, sliders, popups, labels,
// toggles) and exposing the bundled Inter + JetBrains Mono typefaces via
// getTypefaceForFont().
//
// Port source: phases/phase-6-ui/reamix.me JUCE/plugin.css (button, slider,
// menu, checkbox rules) + tokens.css tokens via reamix::theme (ADR-036 D5).
//
// Typefaces are loaded lazily from the font_binary_data target generated by
// juce_add_binary_data() in CMakeLists.txt.

namespace reamix::ui
{

// Sesja 107 iter-5 — juce::TooltipWindow has setOpaque(true) hardcoded in its
// constructor (vendor/JUCE/.../juce_TooltipWindow.cpp:43). When opaque, JUCE
// skips painting the parent layer beneath the component, so alpha values in
// LookAndFeel::drawTooltip have no visible effect — the rect renders as a
// solid block. Subclass flips setOpaque(false) after construction; from
// that point the parent renders first and our drawTooltip alpha blends on
// top, giving real translucency.
//
// Works because both call sites (MainComponent + AdvancedWeightsWindow) pass
// a parent component to the TooltipWindow constructor, so the popup is
// rendered as a child Component (not as an addToDesktop top-level peer with
// fixed flags missing `windowIsSemiTransparent`).
class TransparentTooltipWindow : public juce::TooltipWindow
{
public:
    explicit TransparentTooltipWindow (juce::Component* parent, int delayMs = 600)
        : juce::TooltipWindow (parent, delayMs)
    {
        setOpaque (false);
    }
};

class LookAndFeelReamix : public juce::LookAndFeel_V4
{
public:
    LookAndFeelReamix();
    ~LookAndFeelReamix() override = default;

    // Typeface dispatch (maps juce::Font → bundled TTF).
    juce::Typeface::Ptr getTypefaceForFont (const juce::Font&) override;

    // Buttons — CSS: .rx-btn (plugin.css:130-171), .rx-btn.primary, .rx-btn.play, .rx-btn.stop.
    void drawButtonBackground (juce::Graphics&, juce::Button&,
                               const juce::Colour& backgroundColour,
                               bool isMouseOverButton, bool isButtonDown) override;
    void drawButtonText       (juce::Graphics&, juce::TextButton&,
                               bool isMouseOverButton, bool isButtonDown) override;

    // Linear slider — CSS: .rx-slider (plugin.css:249-277).
    void drawLinearSlider (juce::Graphics&, int x, int y, int width, int height,
                           float sliderPos, float minSliderPos, float maxSliderPos,
                           juce::Slider::SliderStyle, juce::Slider&) override;

    // Sesja 107 iter-4/iter-7/iter-9 — thumb visually 10 px diameter
    // (radius 5). Iter-9: returning 6 (not 5) so the 1 px accent border
    // stroke renders fully INSIDE slider bounds at min + max value
    // positions; at radius=5 the stroke's 0.5 px outer edge slipped past
    // the slider's clip rect at value=0/1 and the border got chopped.
    // drawDefaultTick mirrors this offset.
    int getSliderThumbRadius (juce::Slider&) override { return 6; }

    // CallOutBox (popover host for block kind picker, block edit, etc.).
    // Linux X11/Cairo doesn't pre-clear fresh top-level peer backing
    // buffers; the JUCE default paint leaves transparent pixels outside
    // the rounded path + drop shadow, so X11 backing-buffer noise shows
    // through as "ciemne zglitchowane tło" around the popover.
    void drawCallOutBoxBackground (juce::CallOutBox&, juce::Graphics&,
                                    const juce::Path&, juce::Image&) override;

    // Popup menu — CSS: .rx-menu (plugin.css:583-601).
    void drawPopupMenuBackground (juce::Graphics&, int width, int height) override;
    void drawPopupMenuItem       (juce::Graphics&, const juce::Rectangle<int>& area,
                                  bool isSeparator, bool isActive, bool isHighlighted,
                                  bool isTicked, bool hasSubMenu,
                                  const juce::String& text,
                                  const juce::String& shortcutKeyText,
                                  const juce::Drawable* icon,
                                  const juce::Colour* textColour) override;

    // Label — CSS: .rx (plugin.css:7) base text style.
    void drawLabel (juce::Graphics&, juce::Label&) override;

    // Toggle / checkbox — CSS: .rx-check (plugin.css:443-459).
    void drawToggleButton (juce::Graphics&, juce::ToggleButton&,
                           bool shouldDrawButtonAsHighlighted,
                           bool shouldDrawButtonAsDown) override;

    // Tooltip — sesja 107 iter-4. Semi-transparent dark pill with rounded
    // corners + subtle shadow + soft border. Padding 10×6. Inter Regular Sm
    // text in Fg0. Width capped at 360 px (multi-line wrap above that).
    juce::Rectangle<int> getTooltipBounds (const juce::String& tipText,
                                            juce::Point<int> screenPos,
                                            juce::Rectangle<int> parentArea) override;
    void drawTooltip (juce::Graphics&, const juce::String& text,
                       int width, int height) override;

    // ── Custom draw helpers for reamix-specific primitives ──────────
    // Full implementations arrive at later port steps per ADR-036 D7
    // (step 5 Tooltip/Popover/Menu, step 7 SpliceMarker).

    // Public slot enum — referenced by the FontBlob lookup in .cpp; exposing
    // it publicly keeps the lookup in an anonymous namespace while cleanly
    // separating the binding table from the class itself.
    enum class FaceSlot
    {
        InterRegular = 0,
        InterMedium,
        InterSemiBold,
        InterBold,
        JbmRegular,
        JbmMedium,
        JbmSemiBold,
        NumSlots
    };

    // SpliceMarker — 1px line + 9×7 triangle cap, quality-colored.
    // Colour comes from theme::Good / Warn / Bad. Step 7 will extend.
    static void drawSpliceMarker (juce::Graphics&, juce::Rectangle<float> area,
                                  const juce::Colour& qualityColour);

    // PillBadge — AUTO / qualities / counts. Rounded full-radius, uppercase.
    // Used by ModeTabs AUTO marker (step 3) and block compatibility (step 8).
    static void drawPillBadge (juce::Graphics&, juce::Rectangle<float> area,
                               const juce::String& text,
                               const juce::Colour& textColour,
                               const juce::Colour& backgroundColour);

    // KbdChip — inline keyboard shortcut indicator inside buttons.
    // Used by TransportBar Play/Stop/Insert (step 3) and menu items (step 5).
    static void drawKbdChip (juce::Graphics&, juce::Rectangle<float> area,
                             const juce::String& text,
                             const juce::Colour& textColour,
                             const juce::Colour& backgroundColour);

    // Brand logo — vectorized sun-burst (radial rays + central hole).
    // DEV-082 sesja 112: replaces the prior BinaryData PNG which produced
    // jagged edges on Linux Cairo/Pango at small target sizes (HeaderBar
    // 18px, WaveformView splash 40px) even with bicubic resampling.
    // Bundled as BinaryData::reamixlogo_svg, parsed once via
    // juce::Drawable::createFromImageData and cached as a function-local
    // static. Callers pass any rect — Drawable::drawWithin handles
    // aspect-correct centered placement.
    static void drawBrandLogo (juce::Graphics& g,
                               juce::Rectangle<float> bounds);

private:
    // One Typeface::Ptr per (family, style) pair. Populated lazily on first
    // request; JUCE caches fonts elsewhere but we want typeface identity
    // stable so getStringWidth() is consistent across queries.

    static constexpr std::size_t kNumSlots =
        static_cast<std::size_t> (FaceSlot::NumSlots);
    std::array<juce::Typeface::Ptr, kNumSlots> typefaces_;

    juce::Typeface::Ptr typefaceFor (FaceSlot);
    static FaceSlot resolveSlot (const juce::Font&);

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (LookAndFeelReamix)
};

} // namespace reamix::ui
